### ISSUE TITLE
Bug: 无法添加定时任务，提示「发生未知错误」

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi-plugin-schedule#2]
发送的指令为：

```
schedule 1m -- echo 233
```

回复：

![image](https://github.com/koishijs/koishi-plugin-schedule/assets/20179549/78c46504-54f7-44da-9416-45436b621b83)

日志：

![image](https://github.com/koishijs/koishi-plugin-schedule/assets/20179549/f3038dff-481f-475a-acd8-4dc38524c4d1)

所有依赖的版本均为最新，任意平台均可复现此问题。

截至目前，已有 3 位用户汇报了此问题。

**Comment by KIRA2ZERO** [comment]
我也遇到了这个问题

**Comment by ilharp** [comment]
论坛上有新的用户遇到了此问题，目前共计 5 人遇到此问题。

<https://k.ilharp.cc/4347>

**Comment by buzuosheng** [comment]
我也遇到了这个问题

**Comment by shigma** [comment]
问题现已定位，是工具链的升级所致。

<img width="706" alt="image" src="https://github.com/koishijs/koishi-plugin-schedule/assets/33423008/405b1353-b7e4-488c-9198-bcbbdc6037a5">

将工具链升级后，由于目标的 node 版提高，Session 类中未初始化的成员会被直接设置为 undefined。这些属性本来应该是通过 defineProperty 声明的，现在提前声明了导致它们从不可枚举属性变成可枚举的，从而进一步导致序列化失败（因为可枚举属性会参与序列化，而这些属性有循环引用）。

由于问题并不出在 schedule 插件本身，而在 Session 的序列化上，我们将在下一个版本实装修复。

目前 Koishi 生态中除 schedule 以外没有观察到其他对 Session 进行序列化的插件。因此上述问题的影响范围仅限 schedule 插件。

**Comment by shigma** [comment]
同样受此影响的插件：koishi-plugin-adapter-forward

**Comment by lgc2333** [comment]
+1 same problem
